### ISSUE TITLE
Worldmap: Host which inherit GPS coordinates from host-templates are not displayed in all view

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#139] opened 2017-02-01 20:28 UTC
The individual hostview works

**Comment by mohierf** [comment] 2017-02-01 20:37
Ok, so if an host inherits from a template with GPS coordinates, its personal view is ok but it is not displayed in the global worldmap, right ? A screen capture perharps ?

**Comment by spea1** [comment] 2017-02-01 21:05
Worldmap
![worldmap-all](https://cloud.githubusercontent.com/assets/20840532/22526173/85597b50-e8ca-11e6-8cd6-2ebb6b9a0bd4.jpg)

**Comment by mohierf** [comment] 2017-02-02 04:37
An what if you click on the 25 cluster :)

**Comment by mohierf** [comment] 2017-03-05 11:54
Is it confirmed @spea1 ? I close this because I think it is more related to the backend import script ... if any problem exists. The WebUI displays an host if it has GPS coordinates. It is confirmed by the tests

**Closed as completed by mohierf** 2017-03-05 11:54 UTC
